# Generated by scripts/generate_protos.py. DO NOT EDIT!
# source: common.proto
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ccommon.proto\x12\x06common"\x15\n\x04Uuid\x12\r\n\x05value\x18\x01 \x01(\x0c"\'\n\tHistoryId\x12\x1a\n\x04uuid\x18\x01 \x01(\x0b2\x0c.common.Uuid"&\n\x08RecordId\x12\x1a\n\x04uuid\x18\x01 \x01(\x0b2\x0c.common.Uuid"-\n\x0fPyStyleIdxRange\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03end\x18\x02 \x01(\x03".\n\x10UnsignedIdxRange\x12\r\n\x05start\x18\x01 \x01(\x04\x12\x0b\n\x03end\x18\x02 \x01(\x04";\n\x0fHighlightedText\x12\x0c\n\x04open\x18\x01 \x01(\r\x12\r\n\x05close\x18\x02 \x01(\r\x12\x0b\n\x03raw\x18\x03 \x01(\tb\x06proto3')
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jerakeen._proto.common_pb2', globals())
