# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\x07\x63ontrol\"\xdc\x02\n\x10SendEventRequest\x12\x35\n\x0ehistory_pruned\x18\x01 \x01(\x0b\x32\x1b.control.HistoryPrunedEventH\x00\x12\x37\n\x0fhistory_deleted\x18\x02 \x01(\x0b\x32\x1c.control.HistoryDeletedEventH\x00\x12-\n\nforce_sync\x18\x03 \x01(\x0b\x32\x17.control.ForceSyncEventH\x00\x12;\n\x11settings_reloaded\x18\x04 \x01(\x0b\x32\x1e.control.SettingsReloadedEventH\x00\x12*\n\x08shutdown\x18\x05 \x01(\x0b\x32\x16.control.ShutdownEventH\x00\x12\x37\n\x0fhistory_rebuilt\x18\x06 \x01(\x0b\x32\x1c.control.HistoryRebuiltEventH\x00\x42\x07\n\x05\x65vent\"\x13\n\x11SendEventResponse\"\x14\n\x12HistoryPrunedEvent\"\x15\n\x13HistoryRebuiltEvent\"\"\n\x13HistoryDeletedEvent\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\x10\n\x0e\x46orceSyncEvent\"\x17\n\x15SettingsReloadedEvent\"\x0f\n\rShutdownEvent2M\n\x07\x43ontrol\x12\x42\n\tSendEvent\x12\x19.control.SendEventRequest\x1a\x1a.control.SendEventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDEVENTREQUEST']._serialized_start=27
  _globals['_SENDEVENTREQUEST']._serialized_end=375
  _globals['_SENDEVENTRESPONSE']._serialized_start=377
  _globals['_SENDEVENTRESPONSE']._serialized_end=396
  _globals['_HISTORYPRUNEDEVENT']._serialized_start=398
  _globals['_HISTORYPRUNEDEVENT']._serialized_end=418
  _globals['_HISTORYREBUILTEVENT']._serialized_start=420
  _globals['_HISTORYREBUILTEVENT']._serialized_end=441
  _globals['_HISTORYDELETEDEVENT']._serialized_start=443
  _globals['_HISTORYDELETEDEVENT']._serialized_end=477
  _globals['_FORCESYNCEVENT']._serialized_start=479
  _globals['_FORCESYNCEVENT']._serialized_end=495
  _globals['_SETTINGSRELOADEDEVENT']._serialized_start=497
  _globals['_SETTINGSRELOADEDEVENT']._serialized_end=520
  _globals['_SHUTDOWNEVENT']._serialized_start=522
  _globals['_SHUTDOWNEVENT']._serialized_end=537
  _globals['_CONTROL']._serialized_start=539
  _globals['_CONTROL']._serialized_end=616
# @@protoc_insertion_point(module_scope)
