# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import history_pb2 as history__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in history_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HistoryStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartHistory = channel.unary_unary(
                '/history.History/StartHistory',
                request_serializer=history__pb2.StartHistoryRequest.SerializeToString,
                response_deserializer=history__pb2.StartHistoryReply.FromString,
                _registered_method=True)
        self.EndHistory = channel.unary_unary(
                '/history.History/EndHistory',
                request_serializer=history__pb2.EndHistoryRequest.SerializeToString,
                response_deserializer=history__pb2.EndHistoryReply.FromString,
                _registered_method=True)
        self.CancelHistory = channel.unary_unary(
                '/history.History/CancelHistory',
                request_serializer=history__pb2.CancelHistoryRequest.SerializeToString,
                response_deserializer=history__pb2.CancelHistoryReply.FromString,
                _registered_method=True)
        self.TailHistory = channel.unary_stream(
                '/history.History/TailHistory',
                request_serializer=history__pb2.TailHistoryRequest.SerializeToString,
                response_deserializer=history__pb2.TailHistoryReply.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/history.History/Status',
                request_serializer=history__pb2.StatusRequest.SerializeToString,
                response_deserializer=history__pb2.StatusReply.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/history.History/Shutdown',
                request_serializer=history__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=history__pb2.ShutdownReply.FromString,
                _registered_method=True)


class HistoryServicer:
    """Missing associated documentation comment in .proto file."""

    def StartHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TailHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HistoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.StartHistory,
                    request_deserializer=history__pb2.StartHistoryRequest.FromString,
                    response_serializer=history__pb2.StartHistoryReply.SerializeToString,
            ),
            'EndHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.EndHistory,
                    request_deserializer=history__pb2.EndHistoryRequest.FromString,
                    response_serializer=history__pb2.EndHistoryReply.SerializeToString,
            ),
            'CancelHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelHistory,
                    request_deserializer=history__pb2.CancelHistoryRequest.FromString,
                    response_serializer=history__pb2.CancelHistoryReply.SerializeToString,
            ),
            'TailHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.TailHistory,
                    request_deserializer=history__pb2.TailHistoryRequest.FromString,
                    response_serializer=history__pb2.TailHistoryReply.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=history__pb2.StatusRequest.FromString,
                    response_serializer=history__pb2.StatusReply.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=history__pb2.ShutdownRequest.FromString,
                    response_serializer=history__pb2.ShutdownReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'history.History', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('history.History', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class History:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/history.History/StartHistory',
            history__pb2.StartHistoryRequest.SerializeToString,
            history__pb2.StartHistoryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/history.History/EndHistory',
            history__pb2.EndHistoryRequest.SerializeToString,
            history__pb2.EndHistoryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/history.History/CancelHistory',
            history__pb2.CancelHistoryRequest.SerializeToString,
            history__pb2.CancelHistoryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TailHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/history.History/TailHistory',
            history__pb2.TailHistoryRequest.SerializeToString,
            history__pb2.TailHistoryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/history.History/Status',
            history__pb2.StatusRequest.SerializeToString,
            history__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/history.History/Shutdown',
            history__pb2.ShutdownRequest.SerializeToString,
            history__pb2.ShutdownReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
