from collections.abc import AsyncIterable, Awaitable
import grpc
from . import history_pb2

class HistoryStub:
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    def StartHistory(self, request: history_pb2.StartHistoryRequest, *, timeout: float | None = ...) -> Awaitable[history_pb2.StartHistoryReply]: ...
    def EndHistory(self, request: history_pb2.EndHistoryRequest, *, timeout: float | None = ...) -> Awaitable[history_pb2.EndHistoryReply]: ...
    def CancelHistory(self, request: history_pb2.CancelHistoryRequest, *, timeout: float | None = ...) -> Awaitable[history_pb2.CancelHistoryReply]: ...
    def DeleteHistory(self, request_iterator: AsyncIterable[history_pb2.DeleteHistoryRequest], *, timeout: float | None = ...) -> Awaitable[history_pb2.DeleteHistoryReply]: ...
    def RebuildHistory(self, request: history_pb2.RebuildHistoryRequest, *, timeout: float | None = ...) -> Awaitable[history_pb2.RebuildHistoryReply]: ...
    def TailHistory(self, request: history_pb2.TailHistoryRequest, *, timeout: float | None = ...) -> AsyncIterable[history_pb2.TailHistoryReply]: ...
    def Status(self, request: history_pb2.StatusRequest, *, timeout: float | None = ...) -> Awaitable[history_pb2.StatusReply]: ...
    def Shutdown(self, request: history_pb2.ShutdownRequest, *, timeout: float | None = ...) -> Awaitable[history_pb2.ShutdownReply]: ...
    def RegisterCommandOutput(self, request: history_pb2.RegisterCommandOutputRequest, *, timeout: float | None = ...) -> Awaitable[history_pb2.RegisterCommandOutputResponse]: ...
    def GetCommandOutput(self, request: history_pb2.GetCommandOutputRequest, *, timeout: float | None = ...) -> Awaitable[history_pb2.GetCommandOutputResponse]: ...

