from collections.abc import AsyncIterable, Awaitable
import grpc
from . import history_pb2

class HistoryStub:
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    def StartHistory(self, request: history_pb2.StartHistoryRequest) -> Awaitable[history_pb2.StartHistoryReply]: ...
    def EndHistory(self, request: history_pb2.EndHistoryRequest) -> Awaitable[history_pb2.EndHistoryReply]: ...
    def CancelHistory(self, request: history_pb2.CancelHistoryRequest) -> Awaitable[history_pb2.CancelHistoryReply]: ...
    def TailHistory(self, request: history_pb2.TailHistoryRequest) -> AsyncIterable[history_pb2.TailHistoryReply]: ...
    def Status(self, request: history_pb2.StatusRequest) -> Awaitable[history_pb2.StatusReply]: ...
    def Shutdown(self, request: history_pb2.ShutdownRequest) -> Awaitable[history_pb2.ShutdownReply]: ...
