# Generated by scripts/generate_protos.py. DO NOT EDIT!
from __future__ import annotations

import grpc
from . import history_pb2 as history__pb2

class HistoryStub:
    def __init__(self, channel: grpc.aio.Channel) -> None:
        self.StartHistory = channel.unary_unary(
            '/history.History/StartHistory',
            request_serializer=history__pb2.StartHistoryRequest.SerializeToString,
            response_deserializer=history__pb2.StartHistoryReply.FromString,
        )
        self.EndHistory = channel.unary_unary(
            '/history.History/EndHistory',
            request_serializer=history__pb2.EndHistoryRequest.SerializeToString,
            response_deserializer=history__pb2.EndHistoryReply.FromString,
        )
        self.CancelHistory = channel.unary_unary(
            '/history.History/CancelHistory',
            request_serializer=history__pb2.CancelHistoryRequest.SerializeToString,
            response_deserializer=history__pb2.CancelHistoryReply.FromString,
        )
        self.DeleteHistory = channel.stream_unary(
            '/history.History/DeleteHistory',
            request_serializer=history__pb2.DeleteHistoryRequest.SerializeToString,
            response_deserializer=history__pb2.DeleteHistoryReply.FromString,
        )
        self.RebuildHistory = channel.unary_unary(
            '/history.History/RebuildHistory',
            request_serializer=history__pb2.RebuildHistoryRequest.SerializeToString,
            response_deserializer=history__pb2.RebuildHistoryReply.FromString,
        )
        self.TailHistory = channel.unary_stream(
            '/history.History/TailHistory',
            request_serializer=history__pb2.TailHistoryRequest.SerializeToString,
            response_deserializer=history__pb2.TailHistoryReply.FromString,
        )
        self.Status = channel.unary_unary(
            '/history.History/Status',
            request_serializer=history__pb2.StatusRequest.SerializeToString,
            response_deserializer=history__pb2.StatusReply.FromString,
        )
        self.Shutdown = channel.unary_unary(
            '/history.History/Shutdown',
            request_serializer=history__pb2.ShutdownRequest.SerializeToString,
            response_deserializer=history__pb2.ShutdownReply.FromString,
        )
        self.RegisterCommandOutput = channel.unary_unary(
            '/history.History/RegisterCommandOutput',
            request_serializer=history__pb2.RegisterCommandOutputRequest.SerializeToString,
            response_deserializer=history__pb2.RegisterCommandOutputResponse.FromString,
        )
        self.GetCommandOutput = channel.unary_unary(
            '/history.History/GetCommandOutput',
            request_serializer=history__pb2.GetCommandOutputRequest.SerializeToString,
            response_deserializer=history__pb2.GetCommandOutputResponse.FromString,
        )

