# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"w\n\rSearchContext\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63wd\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\x0f\n\x07host_id\x18\x04 \x01(\t\x12\x15\n\x08git_root\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_git_root\"\x91\x01\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x10\n\x08query_id\x18\x02 \x01(\x04\x12\'\n\x0b\x66ilter_mode\x18\x03 \x01(\x0e\x32\x12.search.FilterMode\x12&\n\x07\x63ontext\x18\x04 \x01(\x0b\x32\x15.search.SearchContext\x12\x0e\n\x06shells\x18\x05 \x03(\t\"/\n\x0eSearchResponse\x12\x10\n\x08query_id\x18\x01 \x01(\x04\x12\x0b\n\x03ids\x18\x02 \x03(\x0c\"%\n\x13PrepareIndexRequest\x12\x0e\n\x06shells\x18\x01 \x03(\t\"\x16\n\x14PrepareIndexResponse*b\n\nFilterMode\x12\n\n\x06GLOBAL\x10\x00\x12\x08\n\x04HOST\x10\x01\x12\x0b\n\x07SESSION\x10\x02\x12\r\n\tDIRECTORY\x10\x03\x12\r\n\tWORKSPACE\x10\x04\x12\x13\n\x0fSESSION_PRELOAD\x10\x05\x32\x90\x01\n\x06Search\x12;\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse(\x01\x30\x01\x12I\n\x0cPrepareIndex\x12\x1b.search.PrepareIndexRequest\x1a\x1c.search.PrepareIndexResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILTERMODE']._serialized_start=405
  _globals['_FILTERMODE']._serialized_end=503
  _globals['_SEARCHCONTEXT']._serialized_start=24
  _globals['_SEARCHCONTEXT']._serialized_end=143
  _globals['_SEARCHREQUEST']._serialized_start=146
  _globals['_SEARCHREQUEST']._serialized_end=291
  _globals['_SEARCHRESPONSE']._serialized_start=293
  _globals['_SEARCHRESPONSE']._serialized_end=340
  _globals['_PREPAREINDEXREQUEST']._serialized_start=342
  _globals['_PREPAREINDEXREQUEST']._serialized_end=379
  _globals['_PREPAREINDEXRESPONSE']._serialized_start=381
  _globals['_PREPAREINDEXRESPONSE']._serialized_end=403
  _globals['_SEARCH']._serialized_start=506
  _globals['_SEARCH']._serialized_end=650
# @@protoc_insertion_point(module_scope)
