# Generated by scripts/generate_protos.py. DO NOT EDIT!
from __future__ import annotations

import grpc
from . import search_pb2 as search__pb2

class SearchStub:
    def __init__(self, channel: grpc.aio.Channel) -> None:
        self.Search = channel.stream_stream(
            '/search.Search/Search',
            request_serializer=search__pb2.SearchRequest.SerializeToString,
            response_deserializer=search__pb2.SearchResponse.FromString,
        )
        self.PrepareIndex = channel.unary_unary(
            '/search.Search/PrepareIndex',
            request_serializer=search__pb2.PrepareIndexRequest.SerializeToString,
            response_deserializer=search__pb2.PrepareIndexResponse.FromString,
        )
        self.SearchCommandOutput = channel.unary_stream(
            '/search.Search/SearchCommandOutput',
            request_serializer=search__pb2.SearchCommandOutputRequest.SerializeToString,
            response_deserializer=search__pb2.OutputSearchMatch.FromString,
        )

