from collections.abc import AsyncIterable, Awaitable
import grpc
from . import search_pb2

class SearchStub:
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    def Search(self, request_iterator: AsyncIterable[search_pb2.SearchRequest]) -> AsyncIterable[search_pb2.SearchResponse]: ...
    def PrepareIndex(self, request: search_pb2.PrepareIndexRequest) -> Awaitable[search_pb2.PrepareIndexResponse]: ...
