# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: semantic.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'semantic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esemantic.proto\x12\x08semantic\"\xf0\x01\n\x0e\x43ommandCapture\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\x16\n\texit_code\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12\x17\n\nhistory_id\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nsession_id\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x10output_truncated\x18\x07 \x01(\x08\x12\x1d\n\x15output_observed_bytes\x18\x08 \x01(\x04\x42\x0c\n\n_exit_codeB\r\n\x0b_history_idB\r\n\x0b_session_id\"\'\n\x13RecordCommandsReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x04\"Q\n\x14\x43ommandOutputRequest\x12\x12\n\nhistory_id\x18\x01 \x01(\t\x12%\n\x06ranges\x18\x02 \x03(\x0b\x32\x15.semantic.OutputRange\")\n\x0bOutputRange\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\"2\n\nOutputLine\x12\x13\n\x0bline_number\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xbb\x01\n\x12\x43ommandOutputReply\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x13\n\x0btotal_bytes\x18\x03 \x01(\x04\x12\x13\n\x0btotal_lines\x18\x04 \x01(\x04\x12#\n\x05lines\x18\x05 \x03(\x0b\x32\x14.semantic.OutputLine\x12\x18\n\x10output_truncated\x18\x06 \x01(\x08\x12\x1d\n\x15output_observed_bytes\x18\x07 \x01(\x04\x32\xa6\x01\n\x08Semantic\x12K\n\x0eRecordCommands\x12\x18.semantic.CommandCapture\x1a\x1d.semantic.RecordCommandsReply(\x01\x12M\n\rCommandOutput\x12\x1e.semantic.CommandOutputRequest\x1a\x1c.semantic.CommandOutputReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'semantic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDCAPTURE']._serialized_start=29
  _globals['_COMMANDCAPTURE']._serialized_end=269
  _globals['_RECORDCOMMANDSREPLY']._serialized_start=271
  _globals['_RECORDCOMMANDSREPLY']._serialized_end=310
  _globals['_COMMANDOUTPUTREQUEST']._serialized_start=312
  _globals['_COMMANDOUTPUTREQUEST']._serialized_end=393
  _globals['_OUTPUTRANGE']._serialized_start=395
  _globals['_OUTPUTRANGE']._serialized_end=436
  _globals['_OUTPUTLINE']._serialized_start=438
  _globals['_OUTPUTLINE']._serialized_end=488
  _globals['_COMMANDOUTPUTREPLY']._serialized_start=491
  _globals['_COMMANDOUTPUTREPLY']._serialized_end=678
  _globals['_SEMANTIC']._serialized_start=681
  _globals['_SEMANTIC']._serialized_end=847
# @@protoc_insertion_point(module_scope)
