from collections.abc import AsyncIterable, Awaitable
import grpc
from . import semantic_pb2

class SemanticStub:
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    def RecordCommands(self, request_iterator: AsyncIterable[semantic_pb2.CommandCapture]) -> Awaitable[semantic_pb2.RecordCommandsReply]: ...
    def CommandOutput(self, request: semantic_pb2.CommandOutputRequest) -> Awaitable[semantic_pb2.CommandOutputReply]: ...
